---
- name: Create the {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    image: "nginx"
    pull: yes
    state: 'started'
    networks:
      - name: honeynet
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/conf.d:/etc/nginx/conf.d"
      - "{{ docker_dir }}/{{ container_name }}/nginx.conf:/etc/nginx/nginx.conf"
      - "{{ docker_dir }}/certbot/conf:/etc/letsencrypt"
      - "{{ docker_dir }}/certbot/www:/var/www/certbot"
    ports:
      - "80:80"
      - "443:443"
    restart_policy: unless-stopped

# - name: Create the certbot container
#   docker_container:
#     name: "certbot"
#     image: "certbot/certbot"
#     pull: yes
#     state: 'started'
#     networks:
#       - name: honeynet
#     volumes:
#       - "{{ docker_dir }}/certbot/conf:/etc/letsencrypt"
#       - "{{ docker_dir }}/certbot/www:/var/www/certbot"
#     restart_policy: unless-stopped