---
- name: Copy script
  ansible.builtin.copy:
    src: roles/containers/mitm-proxy/scripts/reverseproxy.py
    dest: "{{ docker_dir }}/{{ container_name }}/reverseproxy.py"

- name: Copy json
  ansible.builtin.copy:
    src: files/wordpress_containers.json
    dest: "{{ docker_dir }}/{{ container_name }}/wordpress_containers.json"

- name: upload the scripts directory to the docker host
  synchronize: src=roles/containers/mitm-proxy/scripts dest=/tmp

- name: Build mitmproxy image
  docker_image:
    name: mitmproxy-logger
    build:
      path: "/tmp/scripts"
      dockerfile: Dockerfile
    tag: ex6
    state: present
    source: build

- name: Save vars
  set_fact:
    wpContainers: "{{ lookup('file', 'files/wordpress_containers.json') | from_json }}"

- name: Creat Virtual Hostnames string
  set_fact:
    a: "{{ a | default('press.wordpress.0rn.de') + ',' + item.url }}"
  loop: "{{ wpContainers }}"

- name: Create the {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    hostname: "mitmproxy"
    image: mitmproxy-logger:ex4
    state: 'started'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/scripts"
      - "{{ docker_dir }}/{{ container_name }}/logs:/logs"
    networks:
      - name: honeynet
    env:
        'VIRTUAL_HOST': '{{ a }}'
        'VIRTUAL_PORT': '8080'
        'LETSENCRYPT_HOST': '{{ a }}'
        'LETSENCRYPT_EMAIL': 'aron.wiederkehr@gmail.com'
        'LETSENCRYPT_SINGLE_DOMAIN_CERTS': 'true'
    restart_policy: unless-stopped