---
- name: Copy script
  ansible.builtin.copy:
    src: roles/containers/mitm-proxy/scripts/reverseproxy.py
    dest: "{{ docker_dir }}/{{ container_name }}/reverseproxy.py"

- name: upload the scripts directory to the docker host
  synchronize: src=roles/containers/mitm-proxy/scripts dest=/tmp

- name: Build mitmproxy image
  docker_image:
    name: mitmproxy-logger
    build:
      path: "/tmp/scripts"
      dockerfile: Dockerfile
    tag: ex3
    state: present
    source: build



- name: Create the {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    hostname: "mitmproxy"
    image: mitmproxy-logger:ex3
    state: 'started'
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/scripts"
      - "{{ docker_dir }}/{{ container_name }}/logs:/logs"
    networks:
      - name: honeynet
    env:
        'VIRTUAL_HOST': 'press.wordpress.0rn.de'
        'VIRTUAL_PORT': '8080'
        'LETSENCRYPT_HOST': 'press.wordpress.0rn.de'
        'LETSENCRYPT_EMAIL': 'aron.wiederkehr@gmail.com'
    restart_policy: unless-stopped