---
- hosts: all
  become: yes

  tasks:
    - import_tasks: tasks/essential.yml
  
  roles:
    #
    # Basics
    #
    - role: docker
      tags: 
        - docker

    - role: containers/portainer
      tags:
        - portainer
        - containers
      
    - role: containers/nginx-proxy
      tags:
        - proxies
        - nginx
        - containers
      when: enable_nginx

    - role: containers/nginx-dummy
      tags:
        - nginx
        - dummy
        - containers
      when: enable_nginx_dummy

    - role: containers/rproxy_letsencrypt
      tags:
        - rproxy
        - containers
      when: enable_rproxy
    
    - role: containers/mitm-proxy
      tags:
        - mitm
        - proxies
        - containers
      when: enable_mitm
    
    - role: containers/wordpress
      tags:
        - wordpress
        - containers
      when: enable_wordpress

    - role: containers/elk
      tags:
        - elk
        - containers
      when: enable_elk