---
# - name: Install the apt mirror list
#   template:
#     src: sources.list.j2
#     dest: /etc/apt/sources.list
#     owner: root
#     group: root
#     mode: 0644
#     tags: mirrors

- name: Update and upgrade packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot
  reboot:
    msg: Rebooting now ...
  when: reboot_required_file.stat.exists

- name: Install essential packages
  package: 
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Restart SSHD daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed