- name: Create a ELK network
  docker_network:
      name: elk_network

- name: Create ES Volume
  docker_volume:
    volume_name: es-data
    driver: local

- name: Create the {{ container_name }}-elasticsearch container
  docker_container:
    name: '{{ container_name }}-elasticsearch'
    hostname: elasticsearch
    image: 'elasticsearch:{{ version }}'
    pull: yes
    networks:
      - name: honeynet
      - name: elk_network
    state: 'started'
    memory: "{{ es_memory_limit }}"
    ulimits:
      - memlock:-1:-1
    env:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      xpack.security.audit.enabled: 'true'
      xpack.security.http.ssl.enabled: 'false'
      ELASTIC_PASSWORD: '{{ es_password }}'
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart_policy: unless-stopped

- name: Create the {{ container_name }}-kibana container
  docker_container:
    name: '{{ container_name }}-kibana'
    hostname: kibana
    image: 'kibana:{{ version }}'
    pull: yes
    networks:
      - name: honeynet
      - name: elk_network
    state: 'started'
    env:
      ELASTICSEARCH_USERNAME: '{{ es_user }}'
      ELASTICSEARCH_PASSWORD: '{{ es_password }}'
    ports:
      - 5601:5601
    volumes:
    restart_policy: unless-stopped

# - name: Copy logstash files to host machine
#   ansible.builtin.copy:
#     src: roles/containers/elk/files/logstash.conf
#     dest: "{{ docker_dir }}/{{ container_name }}/logstash/pipeline/logstash.conf"

- name: Generate logstash.conf file
  template:
    src: logstash.conf.j2
    dest: "{{ docker_dir }}/{{ container_name }}/logstash/pipeline/logstash.conf"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create the {{ container_name }}-logstash container
  docker_container:
    name: '{{ container_name }}-logstash'
    hostname: 'logstash'
    image: 'logstash:{{ version }}'
    pull: yes
    networks:
      - name: honeynet
      - name: elk_network
    state: 'started'
    env:
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/logstash/pipeline:/usr/share/logstash/pipeline"
      - "{{ docker_dir }}/{{ container_name }}/logstash/config:/usr/share/logstash/config"
    restart_policy: unless-stopped

