---
- name: Create the {{ container_name }} container
  docker_container:
    name: "{{ container_name }}"
    hostname: "dummy"
    image: "nginx"
    pull: yes
    state: 'started'
    networks:
      - name: honeynet
    env:
        'VIRTUAL_HOST': 'dummy.wordpress.0rn.de'
        'VIRTUAL_PORT': '80'
        'LETSENCRYPT_HOST': 'dummy.wordpress.0rn.de'
        'LETSENCRYPT_EMAIL': 'aron.wiederkehr@gmail.com'
    restart_policy: unless-stopped