services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image:     "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    environment:
    - cluster.name=es-cluster
    - node.name=es-node-1
    - path.data=/usr/share/elasticsearch/data
    - http.port=9200
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms${ES_JVM_HEAP} -Xmx${ES_JVM_HEAP}"
  mem_limit: ${ES_MEM_LIMIT}
  ulimits:
    memlock:
    soft: -1
    hard: -1
  volumes:
  - ${ES_MOUNT_DRIVE}:/usr/share/elasticsearch/data
  ports:
  - '9200:9200'
  networks:
  - 'elk_stack'
  healthcheck:
    test: ["CMD", "curl","-s" ,"-f", "-u", "elastic:${ES_PASSWORD}", "http://localhost:9200/_cat/health"]
  # Kibana container. localhost 5601 (ensure this is open on host) --> container 5601. Deployed after Elasticsearch.
  kibana:
    container_name: kibana
    hostname: kibana
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}"
    environment:
    ports:
    - '5601:5601'
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/login"]
      retries: 6
    networks:
    - 'elk_stack'
    depends_on:
    - 'elasticsearch'